<a href="https://colab.research.google.com/github/Xaviera8/datasci_1_loading/blob/main/HHA507CLASS1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Week 1: Introduction to Jupyter Notebooks (Google Colab) and Data Acquisition
Objective:

Familiarize yourself with Jupyter Notebook (Google Colab), practice data acquisition techniques, and begin using GitHub for assignment submissions.
Instructions:
1. Setting Up Google Colab:

    Create a new notebook in Google Colab.
    Familiarize yourself with the Colab interface: exploring the menu options, inserting code and text cells, and using the file browser.

2. Data Acquisition:

    Find and download at least 2-3 different CSV datasets (less than 10MB each) that do not contain any PHI/PII.
    Similarly, find and download 3 XLSX files and 3 JSON files with the same criteria.
    Use pandas to load each of these datasets into separate data frames in your Colab notebook.
    Display the first 10 rows of each dataset in separate code cells.

3. Markdown Practice:

    Add a markdown cell and list the features (columns) of each dataset.
    For each feature, give a brief description of its content/purpose.

3. Submission:

    Create a new GitHub repository named datasci_1_loading in your GitHub account.
    Organize your GitHub repository with the following:
        Within your repository, create a folder named "data" to store your acquired datasets.
        Save your Colab notebook to your GitHub repository.
        Submit the link to your GitHub repository.

In [5]:
import pandas as pd

# Loading Local Files

In [19]:
df2 = pd.read_csv('nba_draft_combine_all_years.csv')

df2.columns

Index(['Unnamed: 0', 'Player', 'Year', 'Draft pick', 'Height (No Shoes)',
       'Height (With Shoes)', 'Wingspan', 'Standing reach', 'Vertical (Max)',
       'Vertical (Max Reach)', 'Vertical (No Step)',
       'Vertical (No Step Reach)', 'Weight', 'Body Fat', 'Hand (Length)',
       'Hand (Width)', 'Bench', 'Agility', 'Sprint'],
      dtype='object')

#Insert Files

In [ ]:
csvs = ['nba_draft_combine_all_years.csv',
        'NBA Season Data.csv']

json_files = ['shoe prices.json',
              'GCB2022v27_percapita_flat_metadata.json']

#First Ten Rows of the First CSV File

In [46]:
df = pd.read_csv(csvs[0])
df[:10]

,Unnamed: 0,Player,Year,Draft pick,Height (No Shoes),Height (With Shoes),Wingspan,Standing reach,Vertical (Max),Vertical (Max Reach),Vertical (No Step),Vertical (No Step Reach),Weight,Body Fat,Hand (Length),Hand (Width),Bench,Agility,Sprint
0,0,Blake Griffin,2009,1.0,80.50,82.00,83.25,105.0,35.5,140.5,32.0,137.0,248.0,8.2,NaN,NaN,22.0,10.95,3.28
1,1,Terrence Williams,2009,11.0,77.00,78.25,81.00,103.5,37.0,140.5,30.5,134.0,213.0,5.1,NaN,NaN,9.0,11.15,3.18
2,2,Gerald Henderson,2009,12.0,76.00,77.00,82.25,102.5,35.0,137.5,31.5,134.0,215.0,4.4,NaN,NaN,8.0,11.17,3.14
3,3,Tyler Hansbrough,2009,13.0,80.25,81.50,83.50,106.0,34.0,140.0,27.5,133.5,234.0,8.5,NaN,NaN,18.0,11.12,3.27
4,4,Earl Clark,2009,14.0,80.50,82.25,86.50,109.5,33.0,142.5,28.5,138.0,228.0,5.2,NaN,NaN,5.0,11.17,3.35
5,5,Austin Daye,2009,15.0,81.75,82.75,86.75,110.0,28.0,138.0,25.0,135.0,192.0,5.5,NaN,NaN,NaN,12.11,3.55
6,6,James Johnson,2009,16.0,79.00,79.75,84.75,105.5,35.0,140.5,30.5,136.0,257.0,12.0,NaN,NaN,18.0,11.21,3.23
7,7,Jrue Holiday,2009,17.0,75.25,76.25,79.00,100.5,34.0,134.5,28.5,129.0,199.0,6.3,NaN,NaN,6.0,10.64,3.21
8,8,Ty Lawson,2009,18.0,71.25,72.50,72.75,94.5,36.5,131.0,29.0,123.5,197.0,6.6,NaN,NaN,14.0,10.98,3.12
9,9,Jeff Teague,2009,19.0,72.25,73.50,79.50,98.5,36.5,135.0,30.5,129.0,175.0,4.5,NaN,NaN,13.0,11.05,3.18

#First Ten Rows of the Second CSV File

In [47]:
df2 = pd.read_csv(csvs[1])
df2[:10]

,Year,Tm,Player,Age,G,MP,PER,TS%,3PAr,FTr,...,D-WORP,Adjusted WORP,Estimated Position,BBRef Pos,Age on Feb 1,Yrs Experience,Height,Weight,Rounded Position,Rounded Age
0,1978,NOJ,Truck Robinson,26,82,3638,15.7,0.481,NaN,0.340,...,1.1,1.1,3.6,4.0,26.33,3.0,79.0,225.0,4.0,26.0
1,1978,BUF,Randy Smith,29,82,3314,19.1,0.521,NaN,0.326,...,-2.3,7.4,1.0,2.0,29.14,6.0,75.0,180.0,1.0,29.0
2,1978,WSB,Elvin Hayes,32,81,3246,17.1,0.489,NaN,0.365,...,3.4,6.5,4.2,4.0,32.21,9.0,81.0,235.0,4.0,32.0
3,1978,BOS,Dave Cowens,29,77,3215,18.6,0.533,NaN,0.233,...,6.1,12.5,3.9,5.0,29.27,7.0,81.0,230.0,4.0,29.0
4,1978,NYK,Bob McAdoo,26,79,3182,22.0,0.567,NaN,0.412,...,2.6,10.6,3.6,5.0,26.36,5.0,81.0,210.0,4.0,26.0
5,1978,NJN,Bernard King,21,79,3092,17.3,0.511,NaN,0.277,...,0.2,5.5,2.8,3.0,21.16,0.0,79.0,205.0,3.0,21.0
6,1978,CHI,Artis Gilmore,28,82,3067,23.5,0.604,NaN,0.531,...,3.2,12.8,5.0,5.0,28.36,6.0,86.0,240.0,5.0,28.0
7,1978,DEN,David Thompson,23,80,3025,23.2,0.578,NaN,0.422,...,-2.4,11.1,1.6,2.0,23.56,2.0,76.0,195.0,2.0,24.0
8,1978,GSW,Rick Barry,33,82,3024,20.9,0.509,NaN,0.243,...,1.4,10.0,2.2,3.0,33.85,11.0,79.0,205.0,2.0,34.0
9,1978,IND,Ricky Sobers,25,79,3019,15.4,0.514,NaN,0.328,...,-0.4,4.2,1.1,1.0,25.05,2.0,75.0,198.0,1.0,25.0